import { cn } from "@/lib/utils";
import "./globals.css";
import { Inter } from "next/font/google";
import Link from "next/link";
import AddCourse from "@/components/course/add-course";
import { buttonVariants } from "@/components/ui/button";
import Provider from "@/components/Provider";
import { getServerSession } from "next-auth";
import { Analytics } from "@vercel/analytics/react";
import SignOut from "@/components/nav/SignOut";
const inter = Inter({ subsets: ["latin"] });
import { ModeToggle } from "@/components/nav/theme-toggle";
export const metadata = {
  title: "ClassEcho",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body
        className={cn(
          inter.className,
          "bg-white dark:bg-gray-950 dark:text-slate-100"
        )}
      >
        <Provider session={session}>
          <header className="h-16 z-30 sticky top-0">
            <nav className="sm:px-6 h-full bg-white/50 backdrop-blur-md px-4 lg:px-10  flex items-center justify-between dark:bg-gray-950/50">
              <Link href={"/"}>ClassEcho</Link>
              {!session ? (
                <ul className="flex items-center gap-5">
                  <li>
                    <Link
                      href={"/register"}
                      className={buttonVariants({ variant: "secondary" })}
                    >
                      Register
                    </Link>
                  </li>
                  <li>
                    <Link
                      href={"/login"}
                      className={buttonVariants({ variant: "secondary" })}
                    >
                      Login
                    </Link>
                  </li>
                </ul>
              ) : (
                <ul className="flex items-center gap-4 ">
                  <li>
                    <AddCourse id={session.user.name!} />
                  </li>
                  <li>
                    <ModeToggle />
                  </li>
                  <li>
                    <SignOut />
                  </li>
                </ul>
              )}
            </nav>
          </header>
          {children}
          <footer>
            <h3 className="text-sm text-center py-5">@2023 ClassEcho</h3>
          </footer>
        </Provider>
        <Analytics />
      </body>
    </html>
  );
}
