import { cn } from "@/lib/utils";
import "./globals.css";
import { Inter } from "next/font/google";
import Link from "next/link";
import AddCourse from "@/components/add-course";
import { buttonVariants } from "@/components/ui/button";
import Provider from "@/components/Provider";
import { getServerSession } from "next-auth";
import SignOut from "@/components/SignOut";
const inter = Inter({ subsets: ["latin"] });
import { ModeToggle } from "@/components/theme-toggle";
export const metadata = {
  title: "ClassEcho",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body
        className={cn(
          inter.className,
          "bg-white dark:bg-gray-950 dark:text-slate-100"
        )}
      >
        <Provider session={session}>
          <nav className="h-16 sm:px-6 bg-white/50 backdrop-blur-md px-4 lg:px-10 z-30 sticky top-0 flex items-center justify-between dark:bg-gray-950/50">
            <Link href={"/"}>ClassEcho</Link>
            {!session ? (
              <div className="flex items-center gap-5">
                <Link
                  href={"/register"}
                  className={buttonVariants({ variant: "secondary" })}
                >
                  Register
                </Link>
                <Link
                  href={"/login"}
                  className={buttonVariants({ variant: "secondary" })}
                >
                  Login
                </Link>
              </div>
            ) : (
              <div className="flex items-center gap-4 ">
                <AddCourse id={session.user.name!} />
                <ModeToggle />
                <SignOut />
              </div>
            )}
          </nav>
          {children}
          <footer>
            <h3 className="text-sm text-center py-5">@2023 ClassEcho</h3>
          </footer>
        </Provider>
        {/* <Analytics /> */}
      </body>
    </html>
  );
}
